### ISSUE TITLE
Jumping and colliding with rising lava and lava balls breaks player movement

### ISSUE THREAD

**Issue by Blamcho** [Blamcho/where-is-my-wife#56]
If the player dies with lava and lava balls while jumping or dashing, the player's movement is broken when he respawns. If the player moves from left to right, the movement is broken.

https://drive.google.com/file/d/1WSq3OrdN-vZ38kxEJsr_frctmgZn69jK/view?usp=sharing

https://drive.google.com/file/d/1pysCGrsXCd2gbSZWFEH7aJATKwqc7QzU/view?usp=sharing

It occurs when the player dies with the lava balls or the lava rise and when respawning he moves very fast

**Comment by Horothenic** [comment]
I cant replicate this!!!!!! D:
